name = "PhysicalDesignSparseQCQP"
uuid = "a21c3934-55fc-4539-9fa9-fc3735815100"
authors = ["Pawel Latawiec <pawel@etiket.dev> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
